---
openapi: 3.0.0
paths:
  /:
    get:
      responses:
        "200":
          description: OK
info:
  title: NestJS Service API
  description: API surface exposed by the NestJS service
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://demo01-poi-backend-demo01.apps.sandbox-m4.g2pi.p1.openshiftapps.com/
    description: (RHDH component deployment)
  - url: http://localhost:3000/
    description: (localhost testing)
